#ifndef VIPJAM_STAGES_H
#define VIPJAM_STAGES_H

#define VIPJAM_CHAIN_ORDER_PENDING_NOTE \
    "VIPJAM_CHAIN_ORDER (0x200F1) is reserved/pending: accepted and " \
    "stored, NOT applied to audio. Process order stays fixed " \
    "(James block, ViPER block, loudness, limiter pinned last) until " \
    "chain + protocol + app land true reorder together."

typedef enum {
    VJ_STAGE_JAMES_TUBE = 0,
    VJ_STAGE_JAMES_COMP,
    VJ_STAGE_JAMES_BASS,
    VJ_STAGE_JAMES_EQ,
    VJ_STAGE_JAMES_ARBEQ,
    VJ_STAGE_JAMES_CONV,
    VJ_STAGE_JAMES_DDC,
    VJ_STAGE_JAMES_LIVEPROG,
    VJ_STAGE_JAMES_XFEED,
    VJ_STAGE_JAMES_STEREO,
    VJ_STAGE_JAMES_REVERB,
    VJ_STAGE_VIPER_CONV,
    VJ_STAGE_VIPER_VHE,
    VJ_STAGE_VIPER_DDC,
    VJ_STAGE_VIPER_SPECTRUM,
    VJ_STAGE_VIPER_IIR,
    VJ_STAGE_VIPER_COLOR,
    VJ_STAGE_VIPER_DIFF,
    VJ_STAGE_VIPER_REVERB,
    VJ_STAGE_VIPER_SPK,
    VJ_STAGE_VIPER_PGC,
    VJ_STAGE_VIPER_FET,
    VJ_STAGE_VIPER_DYNSYS,
    VJ_STAGE_VIPER_BASS,
    VJ_STAGE_VIPER_CLARITY,
    VJ_STAGE_VIPER_CURE,
    VJ_STAGE_VIPER_TUBE,
    VJ_STAGE_VIPER_ANALOGX,
    VJ_STAGE_BASS_MONO,
    VJ_STAGE_LOUDNESS,
    VJ_STAGE_LIMITER,
    VJ_STAGE_COUNT
} vj_stage_t;

#endif
